# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indices', '0009_auto_20171026_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_detail',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
