# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvements', '0002_auto_20171026_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementdetail',
            name='date_start',
            field=models.DateField(null=True, verbose_name='hasta'),
        ),
        migrations.AlterField(
            model_name='agreementdetail',
            name='date_until',
            field=models.DateField(null=True, verbose_name='desde'),
        ),
    ]
