# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvements', '0003_auto_20171102_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='metting',
            name='applied_to',
            field=models.IntegerField(choices=[(1, 'SEGURIDAD Y SALUD OCUPACIONAL'), (2, 'OPERACIONES'), (3, 'RR.HH.'), (4, 'CONTABILIDAD'), (5, 'GERENTE GENERAL'), (6, 'TODOS')], default=6, verbose_name='aplicado a'),
        ),
        migrations.AddField(
            model_name='metting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='metting',
            name='effectiveness',
            field=models.BooleanField(default=False, verbose_name='efectividad'),
        ),
        migrations.AddField(
            model_name='metting',
            name='inconvenient',
            field=models.TextField(blank=True, null=True, verbose_name='inconveniente detectado'),
        ),
        migrations.AddField(
            model_name='metting',
            name='owner',
            field=models.IntegerField(choices=[(1, 'Jefe de SSOMA'), (2, 'Jefe de operaciones'), (3, 'Supervisor de operaciones'), (4, 'RRHH'), (5, 'Contabilidad'), (6, 'GERENTE GENERAL')], default=6, verbose_name='responsable de la mejora'),
        ),
        migrations.AddField(
            model_name='metting',
            name='propose',
            field=models.TextField(blank=True, null=True, verbose_name='propuesta'),
        ),
        migrations.AlterField(
            model_name='metting',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha de generación de propuesta'),
        ),
        migrations.AlterField(
            model_name='metting',
            name='title',
            field=models.CharField(max_length=100, verbose_name='nombre de la mejora'),
        ),
    ]
