# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvements', '0004_auto_20171106_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metting',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='improvements/meetings/', verbose_name='evidencia'),
        ),
    ]
