# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvements', '0005_auto_20171106_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='MettingAppliedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='responsable')),
            ],
        ),
        migrations.RemoveField(
            model_name='metting',
            name='applied_to',
        ),
        migrations.AddField(
            model_name='metting',
            name='applied_to',
            field=models.ManyToManyField(to='improvements.MettingAppliedTo'),
        ),
    ]
