# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuerdos_sst', '0003_auto_20171026_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='number',
            field=models.ImageField(default=0, upload_to='', verbose_name='agreement number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='owner',
            field=models.IntegerField(choices=[(0, 'ASESOR EXTERNO'), (1, 'COMITE SST'), (2, 'RR.HH.'), (3, 'ING. SEGURIDAD'), (4, 'MEDICO OCUPACIONAL'), (5, 'JEFE DE OPERACIONES'), (6, 'GERENTE GENERAL'), (7, 'SUPERVISOR DE OPERACIONES')], default=0, null=True, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='agreementdetail',
            name='owner',
            field=models.IntegerField(choices=[(0, 'ASESOR EXTERNO'), (1, 'COMITE SST'), (2, 'RR.HH.'), (3, 'ING. SEGURIDAD'), (4, 'MEDICO OCUPACIONAL'), (5, 'JEFE DE OPERACIONES'), (6, 'GERENTE GENERAL'), (7, 'SUPERVISOR DE OPERACIONES')], default=0, null=True, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='agreementdetail',
            name='state',
            field=models.IntegerField(choices=[(0, 'pendiente'), (1, 'en proceso'), (2, 'finalizado')], default=0, verbose_name='estado'),
        ),
    ]
