# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuerdos_sst', '0004_auto_20171102_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='number',
            field=models.IntegerField(verbose_name='agreement number'),
        ),
    ]
