# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_worker_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='date_in',
            field=models.DateField(blank=True, null=True, verbose_name='date in'),
        ),
        migrations.AddField(
            model_name='worker',
            name='date_out',
            field=models.DateField(blank=True, null=True, verbose_name='date in'),
        ),
    ]
