# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20171102_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediccontrol',
            name='date_expiration',
            field=models.DateField(default=datetime.datetime.now, verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='type_accident',
            field=models.IntegerField(choices=[(1, 'ACCIDENTES CON PRIMEROS AUXILIOS'), (2, 'ACCCIDENTE CON ATENCION MEDICA'), (3, 'ACCIDENTES CON TIEMPO PERDIDO'), (4, 'ACCIDENTES FATALES'), (7, 'INCIDENTE'), (5, 'INCIDENTES PELIGROS'), (6, 'ENFERMEDADES OCUPACIONALES'), (7, 'ACTOS INSEGUROS')], default=1, verbose_name='Tipo de Accidente'),
        ),
        migrations.AlterField(
            model_name='mediccontrol',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='exam date'),
        ),
    ]
