# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 13:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('main', '0012_auto_20171102_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='legalrequirement',
            name='type_register',
            field=models.IntegerField(choices=[(0, 'Generales'), (1, 'Seguridad Ocupacional'), (2, 'Salud Ocupacional'), (3, 'Ergonomia'), (4, 'Mujer Gestante / Personas con limitaciones'), (5, 'Agentes Quimicos / Tabaco'), (6, 'Cancer'), (7, 'Hostigamiento / Disciminacion / VIH - SIDA'), (8, 'Edificacion'), (9, 'Emergencia'), (10, 'Inspeccion en el Trabajo'), (11, 'Electricidad'), (12, 'NTP'), (13, 'Radiaciones'), (14, 'Sanitarias / Alimentacion'), (15, 'Transporte'), (16, 'Normas Tecnicas Internacionales / NFPA / Otros')], default=0, verbose_name='area/proceso/documento relacionado'),
        ),
        migrations.AlterField(
            model_name='mediccontrol',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Exámen'),
        ),
        migrations.AlterField(
            model_name='mediccontrol',
            name='date_expiration',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Expiración'),
        ),
        migrations.AlterField(
            model_name='mediccontrol',
            name='program',
            field=models.IntegerField(choices=[(0, 'CONSERVACION AUDITIVA'), (1, 'CALIDAD DE VIDA'), (2, 'PROMOCION Y PRESERVACION SALUD VISUAL'), (3, 'PROTECCION A LA MUJER GESTANTE Y EN EDAD FERTIL'), (4, 'PROTECCION RESPIRATORIA'), (5, 'VIGILANCIA CONTRA TME'), (6, 'PROTECCION RADIACION UV'), (7, 'RIESGO GEOLOGICO'), (8, 'NINGUNO')], default=0, verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expiration',
            field=models.DateTimeField(verbose_name='Fecha de Expiración'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='foto'),
        ),
    ]
