# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0006_attachfile'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('main', '0013_auto_20171113_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='work',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='work',
            name='task',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
