# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20171226_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'GERENTE_GENERAL'), (2, 'SUPERVISOR_DE_OPERACIONES'), (3, 'JEFE_DE_OPERACIONES'), (4, 'RRHH_CONTABILIDAD'), (5, 'ASESOR_EXTERNO'), (6, 'OPERARIO'), (7, 'AUXILIAR_DE_ALMACEN'), (8, 'AUXILIAR_DE_LIMPIEZA'), (9, 'AUXILIAR_DE_CONTROL_DE_CALIDAD'), (10, 'AUXILIAR_DE_LAVADO_DE_BOTELLAS'), (11, 'AUXILIAR_DE_CARPINTERIA')], verbose_name='Cargo'),
        ),
    ]
