# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0004_auto_20171024_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='responsable',
            field=models.IntegerField(choices=[(0, 'ASESOR EXTERNO'), (1, 'COMITE SST'), (2, 'RR.HH.'), (3, 'ING. SEGURIDAD'), (4, 'MEDICO OCUPACIONAL'), (5, 'JEFE DE OPERACIONES'), (6, 'GERENTE GENERAL'), (7, 'SUPERVISOR DE OPERACIONES')], default=0, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='events',
            name='type_capacitations',
            field=models.IntegerField(blank=True, choices=[(1, 'INDUCCION'), (2, 'CAPACITACION DE LEY'), (3, 'CAPACITACION ESPECIFICA'), (4, 'CAPACITACION DE SEGURIDAD'), (5, 'CAPACITACION DE SALUD OCUPACIONAL'), (6, 'ENTRENAMIENTO')], default=1, null=True, verbose_name='Tipo Capacitacion'),
        ),
        migrations.AlterField(
            model_name='events',
            name='type_inspeccions',
            field=models.IntegerField(blank=True, choices=[(1, 'INSPECCION DE SEGURIDAD'), (2, 'INSPECCION DE SALUD'), (3, 'OBSERVACION PLANEADA DE TAREAS')], default=1, null=True, verbose_name='TIpo Inspeccion'),
        ),
    ]
