# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0005_auto_20171102_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attaches')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fullcalendar.Events')),
            ],
        ),
    ]
